name: sprint9 application

on:
  pull_request:
    branches: [ main ]
    
jobs:
  linter:
    runs-on: ubuntu:20-04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.16.1
      with:
        reporter: 'github-pr-review'
    - name: run mypy
      uses: jashparekh/mypy-action@v2
      with:
        path: '.'
        mypy_flags: '--verbose'
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}

          Repository: ${{ github.repository }}

          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
